name: NoSpawn
version: 0.35
description: Disable mob spawning in certain areas.
author: JavaWarlord
website: www.valiantmarauders.com
main: com.valiantmarauders.minecraft.nospawn.NoSpawn
commands:
  nospawn:
    description: Main command
    aliases: [nosp]
    usage: 
      /<command> [parameters]
      /<command> pos [1 or 2] - set current location as this position
      /<command> set - create an area from two positions